[package]
name = "e2"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "2", features = ["full", "visit", "extra-traits"] }
petgraph = "0.6"
plotters = "0.3"
plotters-svg = "0.3"
walkdir = "2.3"
clap = { version = "4.5", features = ["derive"] }
proc-macro2 = "1.0"
